trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: Build Solution
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      buildConfiguration: 'Release'

    jobs:
      - job: Build
        displayName: Build and publish solution      
        steps:
        - task: NuGetCommand@2
          displayName: 'Authenticate with BDO-Artifacts NuGet feed'
          inputs:
            command: custom
            arguments: sources update -Name "BDO" -Username "vsts" -Password "$(System.AccessToken)" -StorePasswordInClearText -ConfigFile ./nuget.config
        - task: UseDotNet@2
          inputs:
            version: '5.0.x'
            packageType: runtime

        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '6.x'
          displayName: 'Use .Net Code SDK 6'
        - task: DotNetCoreCLI@2
          displayName: 'Build'
          inputs:
            command: 'build'
            projects: './SpecFlowProjectDemo.sln'
            noCache: true
            arguments: '--configuration $(buildConfiguration)'
        - task: DotNetCoreCLI@2
          displayName: "Publishing azure functions"
          inputs:
            command: publish
            publishWebProjects: false
            projects: './SpecFlowProjectDemo.csproj'
            arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/SpecFlowProjectDemo'
            zipAfterPublish: true
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.ArtifactStagingDirectory)'
            artifactName: 'drop'
          displayName: 'Publish Artifact'
       # - task: SpecFlowPlus@0
        #  inputs:
         #   generatorSource: 'FeatureFolder'
        #    projectFilePath: '$(System.DefaultWorkingDirectory)'
        #    projectLanguage: 'en'
       
        - task: SpecFlowPlus@0
          displayName: 'SpecFlow+ build step.'
          inputs:
            projectFilePath: Features
            projectName: CalculateProject
            testExecutionJson: '$(Build.SourcesDirectory)/SpecSpecFlowProjectDemoFlow/bin/Debug/net6.0/TestExecustion.json'
            bindingAssemblies: '$(Build.SourcesDirectory)/SpecFlowProjectDemo/bin/Debug/net6.0/SpecFlowProjectDemo.dll'