trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: Build Solution
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      buildConfiguration: 'Release'

    jobs:
      - job: Build
        displayName: Build and publish solution      
        steps:
        - task: NuGetCommand@2
          displayName: 'Authenticate with BDO-Artifacts NuGet feed'
          inputs:
            command: custom
            arguments: sources update -Name "BDO" -Username "vsts" -Password "$(System.AccessToken)" -StorePasswordInClearText -ConfigFile ./nuget.config
        - task: UseDotNet@2
          inputs:
            version: '5.0.x'
            packageType: runtime

        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '6.x'
          displayName: 'Use .Net Code SDK 6'
        - task: DotNetCoreCLI@2
          displayName: 'Build'
          inputs:
            command: 'build'
            projects: '.SpecFlowProjectDemo/SpecFlowProjectDemo.sln'
            noCache: true
            arguments: '--configuration $(buildConfiguration)'
        
       
          